server:
  port: 8090

spring:
  config:
    import: optional:configserver:http://localhost:8080
  application:
    name: Gateway

  cloud:
    discovery:
      locator:
        enabled: true

    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
            
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 4Sept2001System.in
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

