spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/api/auth/**

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: ProductCatalogService
          uri: lb://ProductCatalogService
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        - id: ShoppingCartService
          uri: lb://ShoppingCartService
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter

        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/api/orders/**

        - id: PaymentServicePayPal
          uri: lb://PaymentServicePayPal
          predicates:
            - Path=/api/payments/**

        - id: NotificationService
          uri: lb://NotificationService
          predicates:
            - Path=/api/email/**

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://EurekaServer:8761/eureka/
  instance:
    prefer-ip-address: true
