spring:
  application:
    name: PaymentService
  config:
    import: optional:configserver:http://localhost:8888
paypal:
  client-id: Ad6tVrpWb4AR7jFNkdHpP-MjaeGArleRxcbhcCU08CxrtE4-LSPsUftU2OzRSzYiDIo40K88EyJV56hV
  client-secret: EHKtAeuau0ADhQ-howMG6rY7RdamNwvM4oGlUtmKxA_jyL0Y__RQVRQN2CGbgo1-evmmzvsvOmsaQRBn
  mode: sandbox

server:
  port: 8084

eureka:  
  instance:  
    hostname: localhost  
  client:  
    service-url:  
      defaultZone: http://localhost:8761/eureka