spring:
  application:
    name: userservice

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

eureka:
  instance:
    hostname: userservice
  client:
    service-url:
      defaultZone: http://EurekaServer:8761/eureka/
