
spring:
  application:
    name: NotificationService
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: githubjordandeev@gmail.com
    password: tosb yeuu ihzo kkzg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

eureka:  
  instance:  
    hostname: localhost
  client:  
    service-url:  
      defaultZone: http://localhost:8761/eureka



