spring:
  application:
    name: NotificationService

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: githubjordandeev@gmail.com
    password: tosb yeuu ihzo kkzg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

eureka:
  instance:
    hostname: NotificationService
  client:
    service-url:
      defaultZone: http://EurekaServer:8761/eureka/
